name: cortex_of_tasks
description: A Task Management & Tracker App
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  go_router: ^10.0.0
  appwrite: ^9.0.1
  flutter_riverpod: ^2.3.6
  flutter_dotenv: ^5.1.0
  fpdart: ^1.0.0

  uuid: ^3.0.7
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
